version: "3.3"
services:
  chall:
    build:
      context: ./chall/
      dockerfile: Dockerfile
      args:
        - FLAG=${FLAG}
    ports:
      - 3000
    environment:
      - SECRET=REDACTED
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=db
      - DB_HOST=db
    networks:
      - internalapp
      - default

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - 3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=db
    networks:
      - internalapp

networks:
  internalapp:
    internal: true
